import { BaleListing, MaskedSeller, EscrowOrderRecord, Category } from '@/types';

export const MASKED_SELLERS: Record<string, MaskedSeller> = {
  'pnp-001': {
    id: 'pnp-001',
    maskedCode: '#PNP-001',
    supplierTier: 'Gold Vetted Importer',
    godownZone: 'Sanoli Road Godown Hub',
    rating: 4.96,
    totalDispatchedBales: 1420,
    repeatBuyerRate: 96,
    isVerified: true,
    memberSince: 'Oct 2021',
  },
  'pnp-002': {
    id: 'pnp-002',
    maskedCode: '#PNP-002',
    supplierTier: 'Direct Mill Godown',
    godownZone: 'Noorwala Industrial Area',
    rating: 4.88,
    totalDispatchedBales: 980,
    repeatBuyerRate: 92,
    isVerified: true,
    memberSince: 'Jan 2022',
  },
  'pnp-003': {
    id: 'pnp-003',
    maskedCode: '#PNP-003',
    supplierTier: 'Graded Sorting Hub',
    godownZone: 'Barsat Road Sorting Yard',
    rating: 4.92,
    totalDispatchedBales: 2150,
    repeatBuyerRate: 95,
    isVerified: true,
    memberSince: 'Aug 2020',
  },
  'pnp-004': {
    id: 'pnp-004',
    maskedCode: '#PNP-004',
    supplierTier: 'Gold Vetted Importer',
    godownZone: 'Sanoli Road Godown Hub',
    rating: 4.94,
    totalDispatchedBales: 860,
    repeatBuyerRate: 93,
    isVerified: true,
    memberSince: 'Mar 2023',
  },
  'pnp-005': {
    id: 'pnp-005',
    maskedCode: '#PNP-005',
    supplierTier: 'Direct Mill Godown',
    godownZone: 'Barsat Road Sorting Yard',
    rating: 4.85,
    totalDispatchedBales: 640,
    repeatBuyerRate: 89,
    isVerified: true,
    memberSince: 'Nov 2023',
  },
  'pnp-006': {
    id: 'pnp-006',
    maskedCode: '#PNP-006',
    supplierTier: 'Graded Sorting Hub',
    godownZone: 'Noorwala Industrial Area',
    rating: 4.91,
    totalDispatchedBales: 1120,
    repeatBuyerRate: 94,
    isVerified: true,
    memberSince: 'May 2022',
  },
};

// 8 Dynamic Panipat Master Categories Tree
export const CATEGORIES: Category[] = [
  {
    id: 'winter-jackets-outerwear',
    name: 'Winter Jackets & Outerwear',
    slug: 'winter-jackets-outerwear',
    iconName: 'Layers',
    sortOrder: 1,
    isActive: true,
    subCategories: [
      { id: 'heavy-puffers', categoryId: 'winter-jackets-outerwear', name: 'Korean Heavy Puffers (Grade A)', slug: 'heavy-puffers', defaultMoq: 25, isActive: true },
      { id: 'leather-bombers', categoryId: 'winter-jackets-outerwear', name: 'Leather Flight Bombers & Aviators', slug: 'leather-bombers', defaultMoq: 20, isActive: true },
      { id: 'sherpa-truckers', categoryId: 'winter-jackets-outerwear', name: 'Sherpa Lined Trucker Jackets', slug: 'sherpa-truckers', defaultMoq: 25, isActive: true },
      { id: 'quilted-vests', categoryId: 'winter-jackets-outerwear', name: 'Insulated Quilted Winter Vests', slug: 'quilted-vests', defaultMoq: 30, isActive: true },
    ],
  },
  {
    id: 'fleece-sweatshirts',
    name: 'Fleece & Sweatshirts',
    slug: 'fleece-sweatshirts',
    iconName: 'Shirt',
    sortOrder: 2,
    isActive: true,
    subCategories: [
      { id: '450gsm-hoodies', categoryId: 'fleece-sweatshirts', name: '450 GSM Heavyweight Hoodies', slug: '450gsm-hoodies', defaultMoq: 30, isActive: true },
      { id: 'graphic-crewnecks', categoryId: 'fleece-sweatshirts', name: 'Embroidered Graphic Crewnecks', slug: 'graphic-crewnecks', defaultMoq: 30, isActive: true },
      { id: 'track-jackets', categoryId: 'fleece-sweatshirts', name: 'Zipper Track Tops & Warmups', slug: 'track-jackets', defaultMoq: 35, isActive: true },
    ],
  },
  {
    id: 'pants-joggers-cargo',
    name: 'Pants, Joggers & Cargo',
    slug: 'pants-joggers-cargo',
    iconName: 'Scissors',
    sortOrder: 3,
    isActive: true,
    subCategories: [
      { id: 'fleece-joggers', categoryId: 'pants-joggers-cargo', name: 'Heavy Fleece Winter Joggers', slug: 'fleece-joggers', defaultMoq: 30, isActive: true },
      { id: 'tactical-cargo', categoryId: 'pants-joggers-cargo', name: 'Multi-Pocket Tactical Cargo Pants', slug: 'tactical-cargo', defaultMoq: 25, isActive: true },
      { id: 'utility-chinos', categoryId: 'pants-joggers-cargo', name: 'Heavy Twill Utility Chinos', slug: 'utility-chinos', defaultMoq: 25, isActive: true },
    ],
  },
  {
    id: 'jeans-denim-workwear',
    name: 'Jeans & Denim Workwear',
    slug: 'jeans-denim-workwear',
    iconName: 'Sparkles',
    sortOrder: 4,
    isActive: true,
    subCategories: [
      { id: 'heavy-duck-canvas', categoryId: 'jeans-denim-workwear', name: 'USA Heavy Duck Canvas & Chore Coats', slug: 'heavy-duck-canvas', defaultMoq: 25, isActive: true },
      { id: '90s-baggy-denim', categoryId: 'jeans-denim-workwear', name: 'Vintage 90s Baggy Selvedge Denim', slug: '90s-baggy-denim', defaultMoq: 30, isActive: true },
      { id: 'distressed-workwear', categoryId: 'jeans-denim-workwear', name: 'Distressed Workwear Jackets', slug: 'distressed-workwear', defaultMoq: 20, isActive: true },
    ],
  },
  {
    id: 'overcoats-trench',
    name: 'Overcoats & Trench',
    slug: 'overcoats-trench',
    iconName: 'Building',
    sortOrder: 5,
    isActive: true,
    subCategories: [
      { id: 'cashmere-overcoats', categoryId: 'overcoats-trench', name: 'Cashmere & Merino Wool Overcoats', slug: 'cashmere-overcoats', defaultMoq: 20, isActive: true },
      { id: 'wool-trench', categoryId: 'overcoats-trench', name: 'Double-Breasted Wool Trench Coats', slug: 'wool-trench', defaultMoq: 20, isActive: true },
      { id: 'formal-blazers', categoryId: 'overcoats-trench', name: 'Tailored Wool Blazers', slug: 'formal-blazers', defaultMoq: 25, isActive: true },
    ],
  },
  {
    id: 'summer-tees-tops',
    name: 'Summer Tees & Tops',
    slug: 'summer-tees-tops',
    iconName: 'Sun',
    sortOrder: 6,
    isActive: true,
    subCategories: [
      { id: '240gsm-graphic-tees', categoryId: 'summer-tees-tops', name: 'Heavyweight 240+ GSM Graphic Tees', slug: '240gsm-graphic-tees', defaultMoq: 50, isActive: true },
      { id: 'acid-wash-oversized', categoryId: 'summer-tees-tops', name: 'Acid Wash & Mineral Dyed Oversized', slug: 'acid-wash-oversized', defaultMoq: 50, isActive: true },
      { id: 'vintage-polos', categoryId: 'summer-tees-tops', name: 'Vintage Knit & Striped Polos', slug: 'vintage-polos', defaultMoq: 40, isActive: true },
    ],
  },
  {
    id: 'womens-thrift-y2k',
    name: "Women's Thrift & Y2K",
    slug: 'womens-thrift-y2k',
    iconName: 'Heart',
    sortOrder: 7,
    isActive: true,
    subCategories: [
      { id: 'chunky-cardigans', categoryId: 'womens-thrift-y2k', name: 'Chunky Pastel Cardigans & Knits', slug: 'chunky-cardigans', defaultMoq: 30, isActive: true },
      { id: 'cropped-sweats', categoryId: 'womens-thrift-y2k', name: 'Cropped Fleece Sweats & Hoodies', slug: 'cropped-sweats', defaultMoq: 30, isActive: true },
      { id: 'y2k-tops', categoryId: 'womens-thrift-y2k', name: 'Y2K Mesh & Fitted Knit Tops', slug: 'y2k-tops', defaultMoq: 40, isActive: true },
    ],
  },
  {
    id: 'home-furnishings-mink',
    name: 'Home Furnishings & Mink',
    slug: 'home-furnishings-mink',
    iconName: 'Package',
    sortOrder: 8,
    isActive: true,
    subCategories: [
      { id: 'mink-blankets', categoryId: 'home-furnishings-mink', name: 'Double-Ply Embossed Heavy Mink Blankets', slug: 'mink-blankets', defaultMoq: 15, isActive: true },
      { id: 'polar-fleece-throws', categoryId: 'home-furnishings-mink', name: 'Polar Fleece Winter Throws', slug: 'polar-fleece-throws', defaultMoq: 30, isActive: true },
      { id: 'panipat-dhurries', categoryId: 'home-furnishings-mink', name: 'Panipat Cotton & Woolen Floor Rugs', slug: 'panipat-dhurries', defaultMoq: 25, isActive: true },
    ],
  },
];

export const MOCK_BALES: BaleListing[] = [
  {
    id: 'bale-001',
    slug: 'korean-heavy-puffer-jackets-grade-a',
    title: 'Korean Heavy Puffer Jackets (Grade A Cream Lot)',
    shortDescription: 'High-density duck down and poly-fill puffers. Top Korean branded winter outerwear.',
    category: 'winter-jackets-outerwear',
    categoryId: 'winter-jackets-outerwear',
    subCategoryId: 'heavy-puffers',
    categoryLabel: 'Winter Jackets & Outerwear',
    originCountry: 'South Korea',
    originFlag: 'KR',
    sourcingMode: 'both',
    thumbnailUrl: 'https://images.unsplash.com/photo-1548883354-7622d03aca27?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1548883354-7622d03aca27?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1516257984-b1b4d707412e?auto=format&fit=crop&w=800&q=80',
    ],
    weightKg: 80,
    estimatedPieceCount: 72,
    sealedBalePrice: 32000,
    curatedPiecePrice: 480,
    curatedMoq: 25,
    gradeBreakdown: {
      gradeA: 85,
      gradeB: 12,
      gradeC: 3,
    },
    videoClips: [
      {
        id: 'clip-001-a',
        type: 'opening_inspection',
        grade: 'Grade A',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
        durationSeconds: 30,
        label: '30s Raw Opening Inspection (Grade A Sample)',
        description: 'Clean zip pulls, uniform duck down density, intact hood linings with zero seam separation.',
        conditionNotes: ['800+ fill power down retention', 'Clean internal satin linings', 'YKK zippers fully functional'],
      },
      {
        id: 'clip-001-b',
        type: 'godown_walkthrough',
        grade: 'Grade A',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
        durationSeconds: 30,
        label: '30s Godown Lot Walk-Through (Batch Stack)',
        description: 'Live walkthrough of the 80kg steel-strapped batch pallet in Sanoli Road godown yard.',
        conditionNotes: ['Factory export seal intact', 'Dry moisture-controlled storage'],
      },
    ],
    seller: MASKED_SELLERS['pnp-001'],
    godownBatchId: 'BATCH-SANOLI-2026-W09',
    qcVerified: true,
    inStockCount: 6,
    viewCount: 1420,
    inquiryCount: 48,
    isHotDeal: true,
    isFlashArrival: true,
    fabricComposition: '100% Nylon Ripstop Outer, Duck Down & Micro-Poly Fill',
    recommendedResaleChannel: 'Thrift Boutiques, Flea Markets, Retail Outlets',
    expectedGrossMargin: '3.8x - 5.2x Margin',
    tags: ['Korean Puffers', 'Duck Down', 'Grade A', 'Sanoli Hub'],
    createdAt: '2026-08-27T10:00:00Z',
  },
  {
    id: 'bale-002',
    slug: 'vintage-heavy-denim-carhartt-workwear',
    title: 'Vintage Heavy Denim Jackets & Workwear Duck Canvas',
    shortDescription: 'USA imported heritage denim jackets, blanket-lined Detroit work jackets and chore coats.',
    category: 'jeans-denim-workwear',
    categoryId: 'jeans-denim-workwear',
    subCategoryId: 'heavy-duck-canvas',
    categoryLabel: 'Jeans & Denim Workwear',
    originCountry: 'United States',
    originFlag: 'US',
    sourcingMode: 'both',
    thumbnailUrl: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1542272604-780c96856592?auto=format&fit=crop&w=800&q=80',
    ],
    weightKg: 100,
    estimatedPieceCount: 95,
    sealedBalePrice: 44000,
    curatedPiecePrice: 540,
    curatedMoq: 25,
    gradeBreakdown: {
      gradeA: 80,
      gradeB: 18,
      gradeC: 2,
    },
    videoClips: [
      {
        id: 'clip-002-a',
        type: 'opening_inspection',
        grade: 'Grade A',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4',
        durationSeconds: 30,
        label: '30s Raw Opening Inspection (Heavy Denim & Duck Canvas)',
        description: 'Authentic 14oz+ heavy denim, genuine distress patina, metal rivet buttons and blanket lining intact.',
        conditionNotes: ['No dry rot', 'Authentic vintage tags', 'Heavy brass zippers'],
      },
      {
        id: 'clip-002-b',
        type: 'godown_walkthrough',
        grade: 'Grade A',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
        durationSeconds: 30,
        label: '30s Godown Lot Walk-Through (Sorting Bay)',
        description: 'Live look at the 100kg bale stacks freshly unloaded from container shipment at Sanoli Hub.',
        conditionNotes: ['Moisture barrier packaging', 'Verified tare weight'],
      },
    ],
    seller: MASKED_SELLERS['pnp-004'],
    godownBatchId: 'BATCH-SANOLI-2026-W09',
    qcVerified: true,
    inStockCount: 4,
    viewCount: 2310,
    inquiryCount: 76,
    isHotDeal: true,
    isFlashArrival: false,
    fabricComposition: '100% Cotton Selvedge Denim & 12oz Duck Canvas',
    recommendedResaleChannel: 'Vintage Stores, Streetwear Retailers',
    expectedGrossMargin: '4.2x - 6.0x Margin',
    tags: ['USA Denim', 'Carhartt Style', 'Blanket Lined', 'Heavyweight'],
    createdAt: '2026-08-26T14:30:00Z',
  },
  {
    id: 'bale-003',
    slug: 'heavyweight-winter-fleece-hoodies-japan-grade-a',
    title: 'Heavyweight Winter Fleece & Graphic Hoodies (Japan Grade A)',
    shortDescription: 'Japanese 450+ GSM loopback cotton hoodies and embroidered college crewnecks.',
    category: 'fleece-sweatshirts',
    categoryId: 'fleece-sweatshirts',
    subCategoryId: '450gsm-hoodies',
    categoryLabel: 'Fleece & Sweatshirts',
    originCountry: 'Japan',
    originFlag: 'JP',
    sourcingMode: 'both',
    thumbnailUrl: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?auto=format&fit=crop&w=800&q=80',
    ],
    weightKg: 80,
    estimatedPieceCount: 140,
    sealedBalePrice: 27500,
    curatedPiecePrice: 240,
    curatedMoq: 30,
    gradeBreakdown: {
      gradeA: 90,
      gradeB: 8,
      gradeC: 2,
    },
    videoClips: [
      {
        id: 'clip-003-a',
        type: 'opening_inspection',
        grade: 'Grade A',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackSeeTheWorld.mp4',
        durationSeconds: 30,
        label: '30s Raw Opening Inspection (450 GSM Loopback)',
        description: 'Dense loopback cotton, zero pilling, vibrant chest prints, intact drawstrings, oversized fits.',
        conditionNotes: ['Clean collar ribs', 'No print cracking', 'Pristine fleece lining'],
      },
      {
        id: 'clip-003-b',
        type: 'godown_walkthrough',
        grade: 'Grade A',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
        durationSeconds: 30,
        label: '30s Godown Lot Walk-Through (Noorwala Cluster)',
        description: 'Overview of the Noorwala storage bay with Japanese graded fleece inventory ready for dispatch.',
        conditionNotes: ['Sealed bale packaging', 'Inspection scale verified'],
      },
    ],
    seller: MASKED_SELLERS['pnp-002'],
    godownBatchId: 'BATCH-NOORWALA-2026-K11',
    qcVerified: true,
    inStockCount: 9,
    viewCount: 3100,
    inquiryCount: 112,
    isHotDeal: false,
    isFlashArrival: true,
    fabricComposition: '100% French Terry & 450 GSM Brushed Fleece',
    recommendedResaleChannel: 'Campus Stores, Online Boutiques, Thrift Fleas',
    expectedGrossMargin: '3.5x - 4.5x Margin',
    tags: ['Japan Hoodies', 'Heavy Fleece', 'Oversized', '450 GSM'],
    createdAt: '2026-08-28T08:00:00Z',
  },
  {
    id: 'bale-004',
    slug: 'cashmere-merino-wool-overcoats-long-trench',
    title: 'Cashmere & Merino Wool Overcoats & Long Trench Coats',
    shortDescription: 'Tailored winter wool overcoats. Structured shoulders and premium satin lining.',
    category: 'overcoats-trench',
    categoryId: 'overcoats-trench',
    subCategoryId: 'cashmere-overcoats',
    categoryLabel: 'Overcoats & Trench',
    originCountry: 'Italy & Korea',
    originFlag: 'IT',
    sourcingMode: 'bale_only',
    thumbnailUrl: 'https://images.unsplash.com/photo-1539533018447-63fcce2678e3?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1539533018447-63fcce2678e3?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
    ],
    weightKg: 80,
    estimatedPieceCount: 58,
    sealedBalePrice: 38500,
    curatedPiecePrice: 720,
    curatedMoq: 20,
    gradeBreakdown: {
      gradeA: 88,
      gradeB: 10,
      gradeC: 2,
    },
    videoClips: [
      {
        id: 'clip-004-a',
        type: 'opening_inspection',
        grade: 'Grade A',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
        durationSeconds: 30,
        label: '30s Raw Opening Inspection (Silk-Wool Blend)',
        description: 'Double-breasted trench coats and tailored wool overcoats in charcoal, camel and navy.',
        conditionNotes: ['Original horn buttons', 'Flawless satin lining', 'Zero fabric flaws'],
      },
      {
        id: 'clip-004-b',
        type: 'godown_walkthrough',
        grade: 'Grade A',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
        durationSeconds: 30,
        label: '30s Godown Lot Walk-Through (Barsat Yard)',
        description: 'Inspection of the strapped Italian overcoat export lot at Barsat Sorting Yard.',
        conditionNotes: ['Double strapped steel banding', 'Moisture protected'],
      },
    ],
    seller: MASKED_SELLERS['pnp-003'],
    godownBatchId: 'BATCH-BARSAT-2026-B04',
    qcVerified: true,
    inStockCount: 3,
    viewCount: 1890,
    inquiryCount: 54,
    isHotDeal: true,
    isFlashArrival: false,
    fabricComposition: '70% Virgin Wool, 20% Cashmere, 10% Polyamide',
    recommendedResaleChannel: 'High-End Boutiques, Winter Retail Stores',
    expectedGrossMargin: '4.5x - 7.0x Margin',
    tags: ['Cashmere Wool', 'Long Trench', 'Overcoats', 'Premium'],
    createdAt: '2026-08-25T16:00:00Z',
  },
  {
    id: 'bale-005',
    slug: 'vintage-corduroy-overshirts-chore-jackets',
    title: 'Vintage Corduroy Overshirts & Work Chore Jackets',
    shortDescription: 'Japanese 8-wale heavy corduroy shirts, chore work jackets, and lumberjack overshirts.',
    category: 'jeans-denim-workwear',
    categoryId: 'jeans-denim-workwear',
    subCategoryId: 'distressed-workwear',
    categoryLabel: 'Jeans & Denim Workwear',
    originCountry: 'Japan',
    originFlag: 'JP',
    sourcingMode: 'pieces_only',
    thumbnailUrl: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=800&q=80',
    ],
    weightKg: 80,
    estimatedPieceCount: 115,
    sealedBalePrice: 29000,
    curatedPiecePrice: 310,
    curatedMoq: 25,
    gradeBreakdown: {
      gradeA: 82,
      gradeB: 15,
      gradeC: 3,
    },
    videoClips: [
      {
        id: 'clip-005-a',
        type: 'opening_inspection',
        grade: 'Grade A',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4',
        durationSeconds: 30,
        label: '30s Raw Opening Inspection (8-Wale Corduroy)',
        description: 'Terracotta, moss green, deep navy and camel corduroy shirts with heavy weight.',
        conditionNotes: ['No cord balding', 'All buttons present', 'Dense cotton texture'],
      },
      {
        id: 'clip-005-b',
        type: 'godown_walkthrough',
        grade: 'Grade A',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
        durationSeconds: 30,
        label: '30s Godown Lot Walk-Through (Noorwala Hub)',
        description: 'Grading table inspection in progress for curated piece hand-picking.',
        conditionNotes: ['Sorted by colorway', 'Direct boutique ready'],
      },
    ],
    seller: MASKED_SELLERS['pnp-006'],
    godownBatchId: 'BATCH-NOORWALA-2026-K11',
    qcVerified: true,
    inStockCount: 5,
    viewCount: 940,
    inquiryCount: 33,
    isHotDeal: false,
    isFlashArrival: false,
    fabricComposition: '100% Heavy Corduroy Cotton 8-Wale',
    recommendedResaleChannel: 'Thrift Boutiques, Weekend Markets',
    expectedGrossMargin: '3.2x - 4.5x Margin',
    tags: ['Corduroy', 'Chore Jackets', 'Japan Thrift', 'Earth Tones'],
    createdAt: '2026-08-26T11:00:00Z',
  },
  {
    id: 'bale-006',
    slug: 'heavyweight-zipper-bomber-leather-flight-jackets',
    title: 'Heavyweight Zipper Bomber & Leather Flight Jackets',
    shortDescription: 'USA and Korean MA-1 flight bombers, shearling collar aviator jackets, distressed leather.',
    category: 'winter-jackets-outerwear',
    categoryId: 'winter-jackets-outerwear',
    subCategoryId: 'leather-bombers',
    categoryLabel: 'Winter Jackets & Outerwear',
    originCountry: 'USA & Korea',
    originFlag: 'US',
    sourcingMode: 'pieces_only',
    thumbnailUrl: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1516257984-b1b4d707412e?auto=format&fit=crop&w=800&q=80',
    ],
    weightKg: 90,
    estimatedPieceCount: 65,
    sealedBalePrice: 39500,
    curatedPiecePrice: 680,
    curatedMoq: 20,
    gradeBreakdown: {
      gradeA: 84,
      gradeB: 12,
      gradeC: 4,
    },
    videoClips: [
      {
        id: 'clip-006-a',
        type: 'opening_inspection',
        grade: 'Grade A',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackSeeTheWorld.mp4',
        durationSeconds: 30,
        label: '30s Raw Opening Inspection (Flight Nylon & Leather)',
        description: 'MA-1 safety orange lining, heavy-gauge zippers, ribbed cuffs and hem intact.',
        conditionNotes: ['Supple leather & heavy flight nylon', 'Heavy duty zip sliders'],
      },
      {
        id: 'clip-006-b',
        type: 'godown_walkthrough',
        grade: 'Grade A',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
        durationSeconds: 30,
        label: '30s Godown Lot Walk-Through (Sanoli Yard)',
        description: 'Sanoli Road grading desk with curated pieces lot selection.',
        conditionNotes: ['Piece-by-piece verified', 'Ready for boutique shipping'],
      },
    ],
    seller: MASKED_SELLERS['pnp-001'],
    godownBatchId: 'BATCH-SANOLI-2026-W09',
    qcVerified: true,
    inStockCount: 4,
    viewCount: 1650,
    inquiryCount: 62,
    isHotDeal: true,
    isFlashArrival: true,
    fabricComposition: 'Top-Grain Leather & Heavy Flight Nylon Shell',
    recommendedResaleChannel: 'Boutiques, Premium Online Resellers',
    expectedGrossMargin: '4.0x - 6.5x Margin',
    tags: ['Bomber Jackets', 'Leather Flight', 'MA-1 Reversible'],
    createdAt: '2026-08-27T18:00:00Z',
  },
  {
    id: 'bale-007',
    slug: 'korean-chunky-knit-sweaters-pastel-y2k-mix',
    title: 'Korean Chunky Knit Sweaters & Cardigans (Pastel Mix)',
    shortDescription: 'Oversized cable knit sweaters, mohair-blend cardigans, argyle & geometric patterns.',
    category: 'womens-thrift-y2k',
    categoryId: 'womens-thrift-y2k',
    subCategoryId: 'chunky-cardigans',
    categoryLabel: "Women's Thrift & Y2K",
    originCountry: 'South Korea',
    originFlag: 'KR',
    sourcingMode: 'both',
    thumbnailUrl: 'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
    ],
    weightKg: 80,
    estimatedPieceCount: 130,
    sealedBalePrice: 22500,
    curatedPiecePrice: 210,
    curatedMoq: 30,
    gradeBreakdown: {
      gradeA: 86,
      gradeB: 11,
      gradeC: 3,
    },
    videoClips: [
      {
        id: 'clip-007-a',
        type: 'opening_inspection',
        grade: 'Grade A',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
        durationSeconds: 30,
        label: '30s Raw Opening Inspection (Plush Mohair-Blend)',
        description: 'Chunky stitch retention, soft pastel colors, trendy oversized silhouettes.',
        conditionNotes: ['Zero unraveling', 'Plush soft handfeel', 'No snags'],
      },
      {
        id: 'clip-007-b',
        type: 'godown_walkthrough',
        grade: 'Grade A',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
        durationSeconds: 30,
        label: '30s Godown Lot Walk-Through (Barsat Hub)',
        description: 'Barsat Yard knitwear sorting bay.',
        conditionNotes: ['Clean packaging', 'Export tare verified'],
      },
    ],
    seller: MASKED_SELLERS['pnp-003'],
    godownBatchId: 'BATCH-BARSAT-2026-B04',
    qcVerified: true,
    inStockCount: 8,
    viewCount: 1280,
    inquiryCount: 41,
    isHotDeal: false,
    isFlashArrival: false,
    fabricComposition: 'Acrylic-Mohair Blend & 100% Chunky Cotton Knit',
    recommendedResaleChannel: 'Thrift Boutiques, Campus Popups',
    expectedGrossMargin: '3.5x - 4.8x Margin',
    tags: ['Korean Knitwear', 'Chunky Cardigans', 'Pastel Mix'],
    createdAt: '2026-08-25T09:00:00Z',
  },
  {
    id: 'bale-008',
    slug: 'double-ply-heavy-mink-blankets-export-pack',
    title: 'Double-Ply Heavy Mink Blankets (Grade A Export Pack)',
    shortDescription: 'Direct Panipat and Korean embossed floral and geometric heavy 4.5kg - 6kg mink blankets.',
    category: 'home-furnishings-mink',
    categoryId: 'home-furnishings-mink',
    subCategoryId: 'mink-blankets',
    categoryLabel: 'Home Furnishings & Mink',
    originCountry: 'Panipat Mills & Korea',
    originFlag: 'IN',
    sourcingMode: 'bale_only',
    thumbnailUrl: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1539533018447-63fcce2678e3?auto=format&fit=crop&w=800&q=80',
    ],
    weightKg: 100,
    estimatedPieceCount: 36,
    sealedBalePrice: 34500,
    curatedPiecePrice: 1020,
    curatedMoq: 15,
    gradeBreakdown: {
      gradeA: 92,
      gradeB: 6,
      gradeC: 2,
    },
    videoClips: [
      {
        id: 'clip-008-a',
        type: 'opening_inspection',
        grade: 'Grade A',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4',
        durationSeconds: 30,
        label: '30s Raw Opening Inspection (Silk-Touch Microfibre)',
        description: 'Heavyweight double bed king size mink blankets with deep luster and zero fiber shed.',
        conditionNotes: ['Heavy 5kg+ weight per piece', 'Double sided embossed print'],
      },
      {
        id: 'clip-008-b',
        type: 'godown_walkthrough',
        grade: 'Grade A',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
        durationSeconds: 30,
        label: '30s Godown Lot Walk-Through (Panipat Mill Yard)',
        description: 'Factory direct export packaging station in Barsat Road mill.',
        conditionNotes: ['High-density strapping', 'Weatherproof bale wrapper'],
      },
    ],
    seller: MASKED_SELLERS['pnp-005'],
    godownBatchId: 'BATCH-BARSAT-2026-B04',
    qcVerified: true,
    inStockCount: 11,
    viewCount: 2800,
    inquiryCount: 95,
    isHotDeal: true,
    isFlashArrival: true,
    fabricComposition: '100% High-Density Ultra-Fine Polyester Mink Yarn',
    recommendedResaleChannel: 'Winter Wholesalers, Bedding Retail Showrooms',
    expectedGrossMargin: '2.5x - 3.5x Margin',
    tags: ['Mink Blankets', 'Double Ply', 'Panipat Mill Hub', 'Heavy 5kg'],
    createdAt: '2026-08-28T06:00:00Z',
  },
  {
    id: 'bale-009',
    slug: 'vintage-90s-windbreakers-retro-track-jackets',
    title: 'Vintage 90s Windbreakers & Retro Track Jackets',
    shortDescription: 'Japanese and European color-block lightweight nylon windbreakers and retro zip tracks.',
    category: 'fleece-sweatshirts',
    categoryId: 'fleece-sweatshirts',
    subCategoryId: 'track-jackets',
    categoryLabel: 'Fleece & Sweatshirts',
    originCountry: 'Japan & Europe',
    originFlag: 'JP',
    sourcingMode: 'pieces_only',
    thumbnailUrl: 'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=800&q=80',
    ],
    weightKg: 80,
    estimatedPieceCount: 155,
    sealedBalePrice: 23500,
    curatedPiecePrice: 185,
    curatedMoq: 35,
    gradeBreakdown: {
      gradeA: 85,
      gradeB: 12,
      gradeC: 3,
    },
    videoClips: [
      {
        id: 'clip-009-a',
        type: 'opening_inspection',
        grade: 'Grade A',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackSeeTheWorld.mp4',
        durationSeconds: 30,
        label: '30s Raw Opening Inspection (Crinkle Nylon)',
        description: 'Vintage nylon windbreakers with breathable mesh lining and vibrant colorways.',
        conditionNotes: ['Elastic cuffs resilient', 'Zero burn holes', 'Original zips'],
      },
      {
        id: 'clip-009-b',
        type: 'godown_walkthrough',
        grade: 'Grade A',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
        durationSeconds: 30,
        label: '30s Godown Lot Walk-Through (Noorwala Yard)',
        description: 'Live walk-through of the windbreaker lot sorting bins.',
        conditionNotes: ['Grade A verified pieces', 'Fast dispatch ready'],
      },
    ],
    seller: MASKED_SELLERS['pnp-002'],
    godownBatchId: 'BATCH-NOORWALA-2026-K11',
    qcVerified: true,
    inStockCount: 6,
    viewCount: 1150,
    inquiryCount: 39,
    isHotDeal: false,
    isFlashArrival: false,
    fabricComposition: '100% Crinkle Nylon Outer, Breathable Poly-Mesh Inner',
    recommendedResaleChannel: 'Online Thrift Stores, Festival Fleas',
    expectedGrossMargin: '3.8x - 5.5x Margin',
    tags: ['90s Windbreaker', 'Colorblock', 'Retro Track'],
    createdAt: '2026-08-26T08:00:00Z',
  },
  {
    id: 'bale-010',
    slug: 'sherpa-lined-trucker-jackets-quilted-vests',
    title: 'Sherpa Lined Trucker Jackets & Heavy Quilted Vests',
    shortDescription: 'USA workwear sherpa-lined corduroy & denim truckers with warm insulating vests.',
    category: 'winter-jackets-outerwear',
    categoryId: 'winter-jackets-outerwear',
    subCategoryId: 'sherpa-truckers',
    categoryLabel: 'Winter Jackets & Outerwear',
    originCountry: 'United States',
    originFlag: 'US',
    sourcingMode: 'both',
    thumbnailUrl: 'https://images.unsplash.com/photo-1516257984-b1b4d707412e?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1516257984-b1b4d707412e?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=800&q=80',
    ],
    weightKg: 85,
    estimatedPieceCount: 85,
    sealedBalePrice: 32500,
    curatedPiecePrice: 420,
    curatedMoq: 25,
    gradeBreakdown: {
      gradeA: 82,
      gradeB: 15,
      gradeC: 3,
    },
    videoClips: [
      {
        id: 'clip-010-a',
        type: 'opening_inspection',
        grade: 'Grade A',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
        durationSeconds: 30,
        label: '30s Raw Opening Inspection (Sherpa Lining)',
        description: 'Classic western yoke details, snap buttons, thermal quilt linings.',
        conditionNotes: ['Clean sherpa lining', 'Snap buttons crisp', 'Heavy denim shell'],
      },
      {
        id: 'clip-010-b',
        type: 'godown_walkthrough',
        grade: 'Grade A',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
        durationSeconds: 30,
        label: '30s Godown Lot Walk-Through (Sanoli Hub)',
        description: 'Sanoli Road pallet bay overview with heavy trucker bales.',
        conditionNotes: ['Export strapped 85kg', 'Weigh scale tare checked'],
      },
    ],
    seller: MASKED_SELLERS['pnp-004'],
    godownBatchId: 'BATCH-SANOLI-2026-W09',
    qcVerified: true,
    inStockCount: 5,
    viewCount: 1720,
    inquiryCount: 58,
    isHotDeal: false,
    isFlashArrival: true,
    fabricComposition: '100% Cotton Outer, Poly Faux Shearling & Thermal Poly-fil',
    recommendedResaleChannel: 'Winter Retail Markets, Boutiques',
    expectedGrossMargin: '3.6x - 5.0x Margin',
    tags: ['Sherpa Trucker', 'Quilted Vests', 'USA Vintage'],
    createdAt: '2026-08-27T12:00:00Z',
  },
];

// Sample Mock Active Orders for 5-Stage Tracker
export const MOCK_ORDERS: Record<string, EscrowOrderRecord> = {
  'ORD-782190': {
    id: 'ORD-782190',
    orderNumber: 'SP-ESCROW-782190',
    baleId: 'bale-001',
    baleTitle: 'Korean Heavy Puffer Jackets (Grade A Cream Lot)',
    baleThumbnail: 'https://images.unsplash.com/photo-1548883354-7622d03aca27?auto=format&fit=crop&w=800&q=80',
    baleWeightKg: 80,
    sellerMaskedCode: '#PNP-001',
    godownZone: 'Sanoli Road Godown Hub, Panipat',
    buyMode: 'sealed_bale',
    quantityBales: 1,
    subtotal: 32000,
    inspectionShieldFee: 1000,
    platformFee: 0,
    totalPayable: 33000,
    escrowStatus: 'QC_APPROVAL_PENDING',
    currentStageIndex: 2,
    createdAt: '2026-08-28T14:20:00Z',
    estimatedDispatch: 'Today by 6:00 PM IST',
    buyerName: 'Rahul Sharma',
    buyerPhone: '+91 98112 34567',
    buyerBusinessName: 'Urban Vintage Thrift Studio',
    deliveryCity: 'New Delhi',
    deliveryState: 'Delhi NCR',
    deliveryAddress: 'Shop 14, Hauz Khas Village Market, New Delhi - 110016',
    transportPreference: 'V-Trans Panipat Hub',
    inspector: {
      name: 'Vikram S.',
      code: 'PNP-INSP-04',
      phone: '+91 98765 43210',
      assignedAt: '2026-08-28T15:00:00Z',
      verifiedTareWeightKg: 81.4,
      openingVideoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    },
  },
  'ORD-640192': {
    id: 'ORD-640192',
    orderNumber: 'SP-ESCROW-640192',
    baleId: 'bale-002',
    baleTitle: 'Vintage Heavy Denim Jackets & Workwear Duck Canvas',
    baleThumbnail: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=800&q=80',
    baleWeightKg: 100,
    sellerMaskedCode: '#PNP-004',
    godownZone: 'Sanoli Road Godown Hub, Panipat',
    buyMode: 'sealed_bale',
    quantityBales: 2,
    subtotal: 88000,
    inspectionShieldFee: 1000,
    platformFee: 0,
    totalPayable: 89000,
    escrowStatus: 'DISPATCHED_BILTI_UPLOADED',
    currentStageIndex: 3,
    createdAt: '2026-08-27T11:00:00Z',
    estimatedDispatch: 'Dispatched via TCI Freight',
    buyerName: 'Amit Verma',
    buyerPhone: '+91 98220 11223',
    buyerBusinessName: 'Verma Apparel & Co.',
    deliveryCity: 'Jaipur',
    deliveryState: 'Rajasthan',
    deliveryAddress: 'Plot 42, MI Road, Jaipur - 302001',
    transportPreference: 'TCI Freight Panipat',
    inspector: {
      name: 'Rajesh Malik',
      code: 'PNP-INSP-02',
      phone: '+91 98765 88990',
      assignedAt: '2026-08-27T12:00:00Z',
      verifiedTareWeightKg: 202.8,
      openingVideoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4',
      approvedAt: '2026-08-27T16:30:00Z',
    },
    bilti: {
      transporterName: 'TCI Freight Panipat Godown Hub',
      lrNumber: 'TCI-PNP-984421',
      dispatchDate: '2026-08-28T09:30:00Z',
      scanImageUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=80',
    },
  },
  'ORD-551980': {
    id: 'ORD-551980',
    orderNumber: 'SP-ESCROW-551980',
    baleId: 'bale-003',
    baleTitle: 'Heavyweight Winter Fleece & Graphic Hoodies (Japan Grade A)',
    baleThumbnail: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
    baleWeightKg: 80,
    sellerMaskedCode: '#PNP-002',
    godownZone: 'Noorwala Industrial Area, Panipat',
    buyMode: 'curated_lot',
    curatedPieceCount: 30,
    subtotal: 7200,
    inspectionShieldFee: 1000,
    platformFee: 0,
    totalPayable: 8200,
    escrowStatus: 'DELIVERED_SETTLED',
    currentStageIndex: 4,
    createdAt: '2026-08-24T09:00:00Z',
    estimatedDispatch: 'Delivered on 26 Aug 2026',
    buyerName: 'Sneha Patel',
    buyerPhone: '+91 97331 44556',
    buyerBusinessName: 'Pop Thrift Mumbai',
    deliveryCity: 'Mumbai',
    deliveryState: 'Maharashtra',
    deliveryAddress: 'Bandra West, Hill Road, Mumbai - 400050',
    transportPreference: 'V-Trans Express',
    inspector: {
      name: 'Vikram S.',
      code: 'PNP-INSP-04',
      phone: '+91 98765 43210',
      assignedAt: '2026-08-24T10:00:00Z',
      verifiedTareWeightKg: 18.5,
      approvedAt: '2026-08-24T14:00:00Z',
    },
    bilti: {
      transporterName: 'V-Trans Express Panipat Hub',
      lrNumber: 'VT-PNP-771239',
      dispatchDate: '2026-08-24T18:00:00Z',
      scanImageUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=80',
    },
  },
};

export function getBaleBySlug(slug: string): BaleListing | undefined {
  return MOCK_BALES.find((bale) => bale.slug === slug);
}

export function getOrderById(orderId: string): EscrowOrderRecord | undefined {
  return MOCK_ORDERS[orderId] || Object.values(MOCK_ORDERS).find((o) => o.orderNumber === orderId || o.id === orderId);
}

export function getBalesByCategory(category: string, subCategory?: string): BaleListing[] {
  if (!category || category === 'all') {
    if (subCategory && subCategory !== 'all') {
      return MOCK_BALES.filter((bale) => bale.subCategoryId === subCategory);
    }
    return MOCK_BALES;
  }

  return MOCK_BALES.filter((bale) => {
    const matchesCategory = 
      bale.categoryId === category ||
      bale.category === category ||
      (category === 'korean_heavy_puffers' && bale.categoryId === 'winter-jackets-outerwear') ||
      (category === 'vintage_denim_workwear' && bale.categoryId === 'jeans-denim-workwear') ||
      (category === 'heavy_fleece_hoodies' && bale.categoryId === 'fleece-sweatshirts') ||
      (category === 'woolen_overcoats_trench' && bale.categoryId === 'overcoats-trench') ||
      (category === 'mink_fleece_blankets' && bale.categoryId === 'home-furnishings-mink') ||
      (category === 'curated_handpicked_lots' && (bale.sourcingMode === 'pieces_only' || bale.sourcingMode === 'both'));

    if (!matchesCategory) return false;
    if (subCategory && subCategory !== 'all') {
      return bale.subCategoryId === subCategory;
    }
    return true;
  });
}

export function searchBales(query: string, category: string = 'all', subCategory?: string): BaleListing[] {
  let filtered = getBalesByCategory(category, subCategory);
  if (!query.trim()) return filtered;
  
  const q = query.toLowerCase();
  return filtered.filter(
    (bale) =>
      bale.title.toLowerCase().includes(q) ||
      bale.shortDescription.toLowerCase().includes(q) ||
      bale.originCountry.toLowerCase().includes(q) ||
      bale.seller.maskedCode.toLowerCase().includes(q) ||
      bale.tags.some((tag) => tag.toLowerCase().includes(q))
  );
}
