name = "sourcepanipat-web"
compatibility_date = "2024-08-01"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = "out"

[assets]
directory = "out"
not_found_handling = "single-page-application"


[vars]
NEXT_PUBLIC_APP_URL = "https://sourcepanipat-web.sourcepanipat.workers.dev"
NEXT_PUBLIC_TURSO_DATABASE_URL = "libsql://sourcepanipat-sourcpanipat.aws-ap-south-1.turso.io"
TURSO_DATABASE_URL = "libsql://sourcepanipat-sourcpanipat.aws-ap-south-1.turso.io"
NEXT_PUBLIC_TURSO_AUTH_TOKEN = "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3ODc5ODIyOTEsImlkIjoiMDFhMDRjMGMtNTkwMS03NjM5LTkzZWQtZWI2MTA3ZGU0YTY5Iiwia2lkIjoiZDIxY1lJdG9iMmFqSEU0R2ZRdEQyY1VQTXZzai1NcnhyZVBRVHI5WFpZUSIsInJpZCI6ImYzZDNiMzdmLTVlMmItNDlkYi1hMTc3LWQxYzJkN2NlZjNmYSJ9.Emfxh0Aqdcv77_R8j5CTPkKGweNSSt5sscmp08txsppH0dncNbyg87A8EZBgSBRMF8V2gaNoWlZiLMQazyU2DA"
TURSO_AUTH_TOKEN = "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3ODc5ODIyOTEsImlkIjoiMDFhMDRjMGMtNTkwMS03NjM5LTkzZWQtZWI2MTA3ZGU0YTY5Iiwia2lkIjoiZDIxY1lJdG9iMmFqSEU0R2ZRdEQyY1VQTXZzai1NcnhyZVBRVHI5WFpZUSIsInJpZCI6ImYzZDNiMzdmLTVlMmItNDlkYi1hMTc3LWQxYzJkN2NlZjNmYSJ9.Emfxh0Aqdcv77_R8j5CTPkKGweNSSt5sscmp08txsppH0dncNbyg87A8EZBgSBRMF8V2gaNoWlZiLMQazyU2DA"
NEXT_PUBLIC_SUPABASE_URL = "https://aqkbiugtxpnjmkeigdnl.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxa2JpdWd0eHBuam1rZWlnZG5sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc5NTUyMTcsImV4cCI6MjEwMzUzMTIxN30.Fy_2E6qi0HA0n3qQohHFXi1X3zFQhzpKI3jj8lUZmpY"
B2_KEY_ID = "0036d4aac29e1590000000001"
B2_APP_KEY = "K0037wZZH0drTKeUlKwj2qf6GKXdQi4"
B2_BUCKET_NAME = "sourcepanipat-media-bucket"
B2_ENDPOINT = "https://s3.eu-central-003.backblazeb2.com"
B2_REGION = "eu-central-003"
